---
- name: Deploy K3s Cluster and Applications
  hosts: webserver # run on all hosts listen under [webserver] group in inventory.ini

  become: yes # Execute all tasks as the root user

  gather_facts: yes

  vars: # One of the servers will be a master in this cluster - the first one
    k3s_master_ip: "{{hostvars[groups['webserver'][0]]['ansible_host'] | default(groups['webserver'][0])}}"
    k3s_token: "{{ vault_k3s_token }}"
    k3s_url: "https://{{ k3s_master_ip }}:6443"
    k3s_extra_server_args: "--write-kubeconfig-mode=0644"

    # This new section loads variables from encrypted file secrets.yml
  vars_files:
    - vars/secrets.yml # This file contains the k3s_token

  pre_tasks:
    - name: Create k3s_control_nodes and k3s_agent_nodes groups
      ansible.builtin.group_by:
        key: "{{ 'k3s_control_nodes' if ansible_host == k3s_master_ip else 'k3s_agent_nodes' }}"
      changed_when: false

      # --- Localhost Pre-tasks (for Ansible controller - github actions runner or other machine running CI/CD) ---
    - name: Ensure .ssh directory exists on localhost
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'
      changed_when: false
    
    - name: Add remote SSH host key to localhost's known_hosts
      delegate_to: localhost
      become: no
      ansible.builtin.shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts" # append host key to known_hosts so that ansible doesn't stop with a prompt
      changed_when: "shell_result.rc != 0"
      register: shell_result
      ignore_errors: yes

      # --- Remote Server (all servers included in inventory.ini) Pre-tasks ---

    - name: Update apt package cache on all servers
      ansible.builtin.apt: # it's like apt-get update
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite system packages
      ansible.builtin.apt:
        name:
          - curl # for k3s role to download packages
          - python3-pip # for kubernetes
        state: present

    - name: Install Kubernetes Python library for Ansible k8s module
      ansible.builtin.pip:
        name: kubernetes # to talk with k3s
        state: present

    - name: Wait 60 seconds for SSH to become available after server boot
      ansible.builtin.wait_for_connection:
        timeout: 60
        

  roles:
    - role: prometheus.prometheus.node_exporter # Automatic node_exporter setup on 9100 port, systemd creation node_exporter.service | separate from terraform firewall 
    - role: xanmanning.k3s

  
  tasks:     
    # ----- COMMENTED OUT - IT WAS FOR MANUAL DOCKER INSTALLATION FUSING ANSIBLE ----- 


    # - name: Install Docker
    #   ansible.builtin.apt:
    #     name: docker.io
    #     state: present # check if present, if not install it
    #   register: apt_install_docker
    #   until: apt_install_docker is not failed
    #   retries: 5
    #   delay: 10

    # - name: Ensure Docker service is running and enabled on boot
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: yes

    # - name: Run Hello-Worldapp container
    #   ansible.builtin.docker_container:
    #     name: hello-world-app
    #     image: "ghcr.io/mayyyk/devops_playground:latest"
    #     state: started
    #     pull: yes # Forces docker to pull lates version from registry
    #     restart_policy: always
    #     ports:
    #       - "5000:5000"


    # make separation only when needed
    - block: # runs only on master's node (thank's to "when" conditional at the bottom of the block)
      
      - name: Create ghcr.io image pull secret in Kubernetes
        kubernetes.core.k8s: 
          state: present
          kubeconfig: /etc/rancher/k3s/k3s.yaml
          # We define the Secret object directly here
          resource_definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: ghcr-creds
              namespace: default
            type: kubernetes.io/dockerconfigjson
            data:
              # We build the .dockerconfigjson content, base64 encoded
              .dockerconfigjson: "{{ {'auths': {'ghcr.io': {'username': vault_ghcr_username, 'password': vault_ghcr_token, 'auth': (vault_ghcr_username + ':' + vault_ghcr_token) | b64encode}}} | to_json | b64encode }}"
     
      - name: Create directory for K8s manifests on master
        ansible.builtin.file:
          path: /root/k8s-manifests
          state: directory
          mode: '0755'

      - name: Copy K8s manifest files to master node
        ansible.builtin.copy:
          src: ../k8s/ # local K8s folder
          dest: /root/k8s-manifests/
        
      - name: Apply K8s manifests using the k8s module (from community.kubernetes) # This task applies "desired state" to the cluster
        kubernetes.core.k8s:
          state: present
          # Use the kubeconfig file generated by the K3s role, runs on master's node
          kubeconfig: /etc/rancher/k3s/k3s.yaml 
          # Apply the manifest file from the master server's disk
          src: "/root/k8s-manifests/{{ item }}"
        loop: # Do this for every file in the list
          - api-deployment.yml
          - api-service.yml
          - ui-deployment.yml
          - ui-service.yml
          - ingress.yml

      # This conditional ensures this whole block only runs on the master
      when: ansible_host == k3s_master_ip

