name: CI/CD Pipeline - Build and Deploy

on:
  push:
    branches: [master, dev, 'feat/**']
  workflow_dispatch: # Option to run manually from GitHub UI Actions tab

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # push to ghcr.io

    steps:
     - name: check out code
       uses: actions/checkout@v4

     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v3
       with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} # automatically created by github actions

     - name: Generate Docker image tag
       id: generate_tag
       run: |
          # Get branch name (e.g., 'feat/my-fix')
          BRANCH_NAME=$(echo "${{ github.ref_name }}")
          # Clean it up for use as a tag (e.g., 'feat-my-fix')
          TAG=$(echo $BRANCH_NAME | tr '/' '-')
          # If it's the 'main' branch, use 'latest' tag
          if [ "$BRANCH_NAME" == "main" ]; then
            TAG="latest"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

    
     - name: Build and push docker Image for API
       uses: docker/build-push-action@v6
       with:
        context: src # all commands are run from root directory of the repo - /
        file: src/Dockerfile
        push: true
        tags: ghcr.io/mayyyk/devops-api:${{ steps.generate_tag.outputs.tag }}

     - name: Build and push docker Image for UI
       uses: docker/build-push-action@v6
       with:
        context: src_frontend
        file: src_frontend/Dockerfile
        push: true
        tags: ghcr.io/mayyyk/devops-ui:${{ steps.generate_tag.outputs.tag }}

  deploy:
    name: Deploy to DigitalOcean Server using Ansible
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout repository # Cloning whole repo to the runner
        uses: actions/checkout@v4


      - name: Create Known Hosts File
        run: echo "${{ secrets.KNOWN_HOSTS}}" > my_known_hosts # create known_hosts file in root directory of the actions runner
        shell: bash

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug Secrets (Check if Empty)
        # This step uses bash to check if the secrets are empty
        # This avoids the 'length()' function which fails parsing.
        shell: bash
        run: |
          if [ -z "${{ secrets.INVENTORY }}" ]; then
            echo "::error:: Sekret INVENTORY jest PUSTY."
          else
            echo "Sekret INVENTORY jest OK (ma zawartość)."
          fi
          
          if [ -z "${{ secrets.KNOWN_HOSTS }}" ]; then
            echo "::error:: Sekret KNOWN_HOSTS jest PUSTY."
          else
            echo "Sekret KNOWN_HOSTS jest OK (ma zawartość)."
          fi
          
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error:: Sekret SSH_PRIVATE_KEY jest PUSTY."
          else
            echo "Sekret SSH_PRIVATE_KEY jest OK (ma zawartość)."
          fi
        
      - name: Download ansible dependencies
        run: ansible-galaxy install -r ansible_project/requirements.yml # currently there's only prometheus.prometheus collection

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v5
        with:
          # path in repo
          playbook: playbook.yml
          
          directory: ansible_project # go to this directory

          inventory: ${{ secrets.INVENTORY }} # use inventory from secrets, option with file creation didn't work
          


          options: --extra-vars "ansible_ssh_common_args='-o UserKnownHostsFile=../my_known_hosts'"
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASS }}